_wandb:
    value:
        cli_version: 0.21.1
        e:
            zyv37xbnrd1dbtpj7ln2xuofexwlvdp2:
                apple:
                    ecpuCores: 4
                    gpuCores: 32
                    memoryGb: 36
                    name: Apple M4 Max
                    pcpuCores: 10
                    ramTotalBytes: "38654705664"
                codePath: Lab. 1/Lab1_CNNs.ipynb
                codePathLocal: Lab1_CNNs.ipynb
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "162097664000"
                email: giulia.ciacci@edu.unifi.it
                executable: /opt/anaconda3/envs/DLA/bin/python
                git:
                    commit: 5d2effeab24f109421f8e4f446503a59fa2050b4
                    remote: https://github.com/ciacciaaaa/DLA_Labs.git
                host: MacBook-Pro-di-Giulia-3.local
                memory:
                    total: "38654705664"
                os: macOS-15.5-arm64-arm-64bit-Mach-O
                program: /Users/giulia/Desktop/UniFi/Magistrale/DLA/DLA_Labs/Lab. 1/Lab1_CNNs.ipynb
                python: CPython 3.13.5
                root: /Users/giulia/Desktop/UniFi/Magistrale/DLA/DLA_Labs/Lab. 1
                startedAt: "2025-08-22T10:29:49.380997Z"
                writerId: zyv37xbnrd1dbtpj7ln2xuofexwlvdp2
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.13.5
            "5": 0.21.1
            "8":
                - 1
            "12": 0.21.1
            "13": darwin-arm64
batch_size:
    value: 128
epochs:
    value: 30
learning_rate:
    value: 0.001
